services:
  t2addok:
    profiles:
      - tools
    build:
      context: t2addok
    volumes:
      - ./data:/data
      - ./t2addok/update.rb:/update.rb
    environment:
      FETCH_HTTP_HEADERS: ${FETCH_HTTP_HEADERS:-}

  addok:
    build:
      context: addok
    image: ghcr.io/teritorio/elasa-search:master
    volumes:
      - ./data:/data
    environment:
      ADDOK_HOST: "redis"
      ADDOK_ATTRIBUTION: "Sirtaqui / OpenStreetMap"
      ADDOK_LICENCE: "ODbL"
    ports:
      - 7878:7878
    restart: unless-stopped

  redis:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    volumes:
      - redis_cache:/data
    command: redis-server --save ""
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_interval: 1s
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  redis_cache:
