on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    # needs: []
    if: github.ref == 'refs/heads/master'

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Docker Build and Push t2addok
        uses: cartoway/docker-compose-build-push-action@main
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          project: teritorio/elasa-search-t2addok
          service: t2addok

      - name: Docker Build and Push Addok
        uses: cartoway/docker-compose-build-push-action@main
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          project: teritorio/elasa-search-addok
          service: addok
